name: Release

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - run: npm ci
      - run: npm run test

  release:
    runs-on: ubuntu-latest

    needs: test
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/v')

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Extract tags
        run: |
          new_tag='${{ github.ref_name }}'
          new_tag_num="$(echo "$new_tag" | sed 's/^v//')"
          previous_tag=v"$((new_tag_num-1))"
          if ! git tag | grep -q "$previous_tag"; then
            previous_tag=''
          fi

          echo previous_tag="$previous_tag" >> $GITHUB_ENV
          echo new_tag="$new_tag" >> $GITHUB_ENV

      - name: Generate changelog
        run: |
          echo '# Changelog' > changelog.md
          echo >> changelog.md
          if [ -z "$previous_tag" ]; then
            git log --oneline HEAD >> changelog.md
          else
            git log --oneline "$previous_tag"..HEAD >> changelog.md
          fi
          sed -Ei 's/^[a-zA-Z0-9]/- \0/' changelog.md

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Build release artifacts
        run: |
          npm ci
          npm run clean
          npm run build

      - uses: fregante/setup-git-user@v1
      - name: Commit, tag and push built release artifacts
        run: |
          git add --force dist
          git commit -m "$new_tag" || exit 0

          git tag -d "$new_tag"
          git tag "$new_tag"
          git push -f origin "$new_tag"

      - uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.new_tag }}
          body_path: changelog.md
